# Generated by Django 4.0 on 2022-02-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('preview', models.TextField(max_length=500)),
                ('content', models.TextField(max_length=1000)),
                ('posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
